# Generated by Django 4.1.4 on 2023-01-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_delete_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=150)),
                ('product_colour', models.CharField(max_length=50)),
                ('seller_id', models.CharField(max_length=150)),
                ('selling_price', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=500)),
                ('mobile_no', models.CharField(max_length=15)),
            ],
        ),
    ]
