# Generated by Django 4.1.4 on 2023-01-03 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
